channels:
  - https://icxc.cfa.harvard.edu/aspect/ska3-conda/flight
dependencies:
  - attitude_error_mon
  - aca_hi_bgd
  - aca_weekly_report
  - acq_stat_reports
  - acdc
  - aimpoint_mon
  - aperoll
  - astromon
  - annie
  - fid_drift_mon
  - guide_stat_reports
  - fss_check
  - jobwatch
  - kalman_watch
  - perigee_health_plots
  - schedule_view3
  - ska_report_ranges
  - ska_trend
  - skare3_tools
  - vv_trending
  - twiki-wg
  - obc_rate_noise_plots
  